FROM python:3.11

WORKDIR /app

# Instala DVC y otras dependencias necesarias
RUN pip install --no-cache-dir dvc

COPY . .

# Instala dependencias Python de tu proyecto (ajusta si usas otro archivo)
RUN pip install -r requirements.txt

CMD ["bash", "scripts/run_dvc.sh"]