data:
  drive: 'https://drive.google.com/uc?/export=download&id=1JGrXjTZsn2IkPesMQ_9E_yYRQ-VfBZ7q'
  local_path: 'data/data.csv'

wandb:
  dataset:
    raw:
      artifact: 'ernestoserize-constructor-university/leuko-ml/acute-stroke-clinical-data:v0'
    selected:
      artifact: 'ernestoserize-constructor-university/leuko-ml/acute-stroke-selected:v2'
  
  model:
    knn:
      artifact: 'ernestoserize-constructor-university/leuko-ml/knn:v0'
    svc:
      artifact: 'ernestoserize-constructor-university/leuko-ml/svc:v0'
