name: leuko-cml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  servos:
    name: Build, Run Server & Execute Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DVC and CML
        run: pip install dvc[gs] dvc-gdrive cml

      - name: Check Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build Docker containers
        run: docker compose build

      - name: Start server container
        run: docker compose up -d server

      - name: Wait for server
        run: |
          until curl -s http://localhost:8080/ping > /dev/null; do
            echo "Waiting for server..."
            sleep 2
          done
          echo "Server is ready."

      - name: Run runner container (DVC Pipeline)
        run: docker compose run --rm runner

      - name: Upload knn.joblib
        uses: actions/upload-artifact@v4
        with:
          name: knn-model
          path: outputs/knn.joblib

      - name: Upload exported CSV
        uses: actions/upload-artifact@v4
        with:
          name: predictions-csv
          path: outputs/exported_data.csv

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Report" > report.md
          echo "\n### Preview of Output CSV" >> report.md
          head -n 10 outputs/exported_data.csv >> report.md
          cml comment create report.md

      - name: Shutdown services
        if: always()
        run: docker compose down
